name: Documentation

on:
  push:
    tags:
      - v*

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Check if tag is latest
        run: |
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          if [ "$LATEST_TAG" != "${{ github.ref_name }}" ]; then
            echo "Current tag ${{ github.ref_name }} is not the latest tag ($LATEST_TAG). Skipping."
            exit 1
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install zensical
      - run: zensical build --clean
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@v4
        id: deployment
